routes:
  /api/v1:
    /topics:
      /:
        GET: Topics.All
      /{id}/headlines:
        GET: Headlines.All
      /{id}/headlines/count:
        GET: Headlines.Count

    /headlines:
      /{id}/story:
        GET: Stories.Get
      /search:
        GET: Headlines.Search

    /sources:
      /:
        GET: Sources.All

    /stories:
      /{id}/summarize:
        GET: Stories.Summarize
  
  /:
    ANY: SPA.Index